services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-gsheets-server
    ports:
      - "8080:8080"
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      BASE_URL: ${BASE_URL:-http://localhost:8080}
      PORT: 8080
    command: python -m mcp_gsheets.server
